# src/main/resources/application-dev.yml
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_MAIL_USERNAME}
    password: ${DEV_MAIL_PASSWORD}
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    default-encoding: UTF-8
