# src/main/resources/application-dev.yml
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${DEV_MAIL_USERNAME}
    password: ${DEV_MAIL_PASSWORD}
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    default-encoding: UTF-8

  datasource:
    url: jdbc:h2:mem:desiKart
    driver-class-name: org.h2.Driver
    username: sa
    password: desiKart

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
    level:
      org.springframework.boot.context.config: DEBUG
